param(
  [ValidateSet("youtube", "mp4")]
  [string]$SourceType = "youtube",
  [string]$SourceValue = "https://www.youtube.com/watch?v=demo",
  [string]$VideoTitle = "Local Test Video",
  [string]$ChannelName = "Local Test Channel",
  [string]$PublishDate = "",
  [string]$Duration = "00:10:00",
  [int]$DurationSeconds = 600,
  [string]$TranscriptFile = "",
  [switch]$ServeDashboard,
  [int]$Port = 8000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$pythonExe = Join-Path $root ".venv\Scripts\python.exe"
$renderScript = Join-Path $root "skills\yt-deep-note-pipeline\scripts\render_prompt.py"
$promptTemplate = Join-Path $root "skills\yt-deep-note-pipeline\references\yt-note-prompt-zh-tw.md"

if (-not (Test-Path $pythonExe)) {
  throw ".venv Python not found: $pythonExe"
}
if (-not (Test-Path $renderScript)) {
  throw "render_prompt.py not found: $renderScript"
}
if (-not (Test-Path $promptTemplate)) {
  throw "Prompt template not found: $promptTemplate"
}

if ([string]::IsNullOrWhiteSpace($PublishDate)) {
  $PublishDate = Get-Date -Format "yyyy-MM-dd"
}

$year = Get-Date -Format "yyyy"
$today = Get-Date -Format "yyyy-MM-dd"
$safeTitle = ($VideoTitle -replace "[^0-9A-Za-z\- ]", "").Trim() -replace "\s+", "-"
if ([string]::IsNullOrWhiteSpace($safeTitle)) {
  $safeTitle = "video-note"
}
$dateSlug = "$today-$safeTitle"
$noteId = "note-" + (Get-Date -Format "yyyyMMddHHmmss")

$dataDir = Join-Path $root "data"
$notesDir = Join-Path $root ("notes\" + $year)
$inputsDir = Join-Path $root "inputs\transcripts"
$outputsDir = Join-Path $root "outputs\prompts"
$indexPath = Join-Path $dataDir "notes-index.json"
$notePath = Join-Path $notesDir ($dateSlug + ".md")
$renderedPromptPath = Join-Path $outputsDir ($dateSlug + ".prompt.md")

New-Item -ItemType Directory -Force $dataDir | Out-Null
New-Item -ItemType Directory -Force $notesDir | Out-Null
New-Item -ItemType Directory -Force $inputsDir | Out-Null
New-Item -ItemType Directory -Force $outputsDir | Out-Null

if ([string]::IsNullOrWhiteSpace($TranscriptFile)) {
  $TranscriptFile = Join-Path $inputsDir "sample_transcript.txt"
}

if (-not (Test-Path $TranscriptFile)) {
  @"
[00:00:01] This is a local transcript sample.
[00:00:08] Replace this with real Whisper output.
[00:00:15] Keep each line in [HH:MM:SS] format.
"@ | Set-Content -Path $TranscriptFile -Encoding UTF8
}

$renderArgs = @(
  $renderScript,
  "--template", $promptTemplate,
  "--source-type", $SourceType,
  "--source-value", $SourceValue,
  "--video-title", $VideoTitle,
  "--channel-name", $ChannelName,
  "--publish-date", $PublishDate,
  "--duration", $Duration,
  "--duration-seconds", $DurationSeconds,
  "--note-id", $noteId,
  "--date-slug", $dateSlug,
  "--transcript-file", $TranscriptFile,
  "--out", $renderedPromptPath
)

& $pythonExe @renderArgs
if ($LASTEXITCODE -ne 0) {
  throw "render_prompt.py failed with exit code $LASTEXITCODE"
}

$transcriptText = Get-Content -Raw -Path $TranscriptFile -Encoding UTF8

$noteContent = @"
# $VideoTitle | Deep Reading Note (Local Test)

> Source: $SourceValue
> Channel: $ChannelName
> Publish Date: $PublishDate
> Duration: $Duration
> Generated Date: $today

## One-line Summary
This is a local test note generated by run-local-test.ps1.

## Transcript (with timestamps)
$transcriptText

## Deep Reading Note
- Purpose: validate local data flow (prompt/markdown/index/dashboard).
- Next: replace this template with real model output.
"@

$noteContent | Set-Content -Path $notePath -Encoding UTF8

$indexItems = @()
if (Test-Path $indexPath) {
  $raw = Get-Content -Raw -Path $indexPath -Encoding UTF8
  if (-not [string]::IsNullOrWhiteSpace($raw)) {
    $parsed = $raw | ConvertFrom-Json
    if ($parsed -is [System.Array]) {
      $indexItems = @($parsed)
    } else {
      $indexItems = @($parsed)
    }
  }
}

$newItem = [PSCustomObject]@{
  id               = $noteId
  title            = "$VideoTitle | Deep Reading Note"
  date             = $today
  tags             = @("youtube", "deep-reading", "zh-TW", "local-test")
  summary          = "Local test pipeline output."
  markdown_path    = ("notes/{0}/{1}.md" -f $year, $dateSlug)
  source_type      = $SourceType
  source_value     = $SourceValue
  duration_seconds = $DurationSeconds
  created_at       = (Get-Date).ToString("o")
}

$indexItems = @($indexItems | Where-Object { $_.id -ne $noteId })
$indexItems += $newItem
$indexItems | ConvertTo-Json -Depth 8 | Set-Content -Path $indexPath -Encoding UTF8

Write-Host ""
Write-Host "Local test completed." -ForegroundColor Green
Write-Host "Prompt: $renderedPromptPath"
Write-Host "Note:   $notePath"
Write-Host "Index:  $indexPath"

if ($ServeDashboard) {
  $serverProc = Start-Process -FilePath $pythonExe -ArgumentList @("-m", "http.server", "$Port") -WorkingDirectory $root -PassThru
  Start-Sleep -Seconds 1
  $url = "http://localhost:$Port/skills/yt-deep-note-pipeline/assets/dashboard-template/"
  Start-Process $url | Out-Null
  Write-Host "Dashboard server started (PID: $($serverProc.Id)) at $url" -ForegroundColor Cyan
}
